# -*- coding: utf-8 -*-
"""P-112 Data Story - 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1adPHv-Nyk6lvS-lLxAg3QJzfC-j-hY

## **Project 112 - Data Story -1** 
This is the project where we analyse the data about people who were given reminders to save money and who weren’t.

This is a very intresting *Data Analysis project*.

## ***Developed By J Ajitesh***
"""

from google.colab import files
data_to_load = files.upload()

"""We have successfully imported our required csv data file."""

import csv
import plotly.express as px
import pandas as pd
import statistics
import plotly.graph_objects as go
import numpy as np

"""We have imported all the necessary python libraries to run our project."""

df = pd.read_csv("data.csv")
print(df)

"""We used a `read_csv` function to read our csv file and printed it using `print()` function"""

# Use a scatter graph to show the the amount saved by females and males
fig = px.scatter(df, y= "quant_saved", color = "female")
fig.show()

"""Analysis: 
1. Blue Color is for boys.
2. Yellow Color is for girls.
3. The maximum amount was saved by a female(7,353.69).
4. There are a few outliners who saved more than 2000.
5. Many femailes are present in the range from 0 to 4k
"""

with open("data.csv", newline = "") as f:
   reader = csv.reader(f)
   savings_data = list(reader)

savings_data.pop(0)
print(savings_data)

# find the total number of males and females
total_entries = len(savings_data)
females = 0

for i in savings_data:
   if int(i[1]) == 1:
      females += 1


fig = go.Figure(go.Bar(x = ["Females", "Males"], y = [females, total_entries - females]))
fig.show()

"""There are around 8361 females and 4929 males(total count).

We can observe that there are more number of females than males who participated in the activity.

"""

all_savings = []
for i in savings_data:
   all_savings.append(float(i[0]))

print(f"Mean of the Data- {statistics.mean(all_savings)}")
print(f"mode of the Data- {statistics.mode(all_savings)}")
print(f"Median of the Data- {statistics.median(all_savings)}")

"""We have calculated the mean, median and mode for the total data.

We can observe that there is a large variation between mean and median which is caused by the outliners.
"""

females = []
males = []

for i in savings_data: 
   if int(i[1]) == 1:
      females.append(float(i[0]))
   else:
      males.append(float(i[0]))

print(f"Mean of the total females- {statistics.mean(females)}")
print(f"Mode of the total females- {statistics.mode(females)}")
print(f"Median of the total females- {statistics.median(females)}")
print()
print(f"Mean of the total males- {statistics.mean(males)}")
print(f"Mode of the total males- {statistics.mode(males)}")
print(f"Median of the total males- {statistics.median(males)}")

"""The large variation in the mean and median is caused by the outliners.

The median and the mode for males and females is same.

The mean of the males is higher than mean of the females.
"""

print(f"Standard deviation of the entire data- {statistics.stdev(all_savings)}")
print(f"Standard deviation for females- {statistics.stdev(females)}")
print(f"Standard deviation for males- {statistics.stdev(males)}")

"""The Standard deviation is higher for males when compared to females."""

gender = []
savings = []
for i in savings_data:
   if float(i[1]) != 0:
      gender.append(float(i[1]))
      savings.append(float(i[0]))

correlation_for_data = np.corrcoef(gender, savings)

print("Correlation between the person's gender and savings", {correlation_for_data[1,0]})

"""We found out the correlation for the gender of the person and the amount saved."""